<?php

return [
    'support_type' => [
        ['value' => 'text', 'text' => '文本框 text', 'data-type' => ['varchar(100)', 'text']],
        ['value' => 'hidden', 'text' => '隐藏域 hidden', 'data-type' => ['int(11)', 'tinyint(4)', 'varchar(100)', 'float(18,2)', 'decimal(18,2)', 'double(18,2)', 'text', 'longtext', 'json']],
        ['value' => 'check', 'text' => '是否 check', 'data-type' => ['tinyint(1)']],
        ['value' => 'integer', 'text' => '整数 integer', 'data-type' => ['int(11)']],
        ['value' => 'number', 'text' => '小数 number', 'data-type' => ['decimal(18,2)', 'float(18,2)', 'double(18,2)']],
        ['value' => 'password', 'text' => '密码框 password', 'data-type' => ['varchar(100)']],
        ['value' => 'color', 'text' => '颜色选择 color', 'data-type' => ['varchar(100)']],
        ['value' => 'date', 'text' => '日期格式 date', 'data-type' => ['date', 'datetime', 'int(11)']],
        ['value' => 'datetime', 'text' => '时间格式 datetime', 'data-type' => ['datetime', 'int(11)']],
        ['value' => 'select', 'text' => '下拉框 select', 'data-type' => ['int(11)', 'varchar(100)']],
        ['value' => 'radiogroup', 'text' => '单选组 radiogroup', 'data-type' => ['int(11)', 'varchar(100)']],
        ['value' => 'checkgroup', 'text' => '多选组 checkgroup', 'data-type' => ['varchar(200)', 'int(11)', 'text', 'longtext', 'json']],
        ['value' => 'linkage', 'text' => '联动下拉 linkage', 'data-type' => ['varchar(200)', 'text', 'json']],
        ['value' => 'textarea', 'text' => '备注型 textarea', 'data-type' => ['text', 'varchar(200)', 'longtext']],
        ['value' => 'upfile', 'text' => '文件上传 upfile', 'data-type' => ['varchar(200)']],
        ['value' => 'upimg', 'text' => '图片上传 upimg', 'data-type' => ['varchar(200)']],
        ['value' => 'qiniu', 'text' => '7牛文件上传 qiniu', 'data-type' => ['varchar(200)']],
        ['value' => 'txupload', 'text' => '腾讯流媒体上传', 'data-type' => ['varchar(200)']],
        ['value' => 'txupimg', 'text' => '腾讯图片上传', 'data-type' => ['varchar(200)']],
        ['value' => 'txupgroup', 'text' => '腾讯多图片上传 txupgroup', 'data-type' => ['text', 'varchar(300)', 'json']],
        ['value' => 'upgroup', 'text' => '多文件上传 upgroup', 'data-type' => ['text', 'varchar(300)', 'json']],
        ['value' => 'upimggroup', 'text' => '多图片上传 upimggroup', 'data-type' => ['text', 'varchar(300)', 'json']],
        ['value' => 'telephone', 'text' => '电话号码 telephone', 'data-type' => ['varchar(200)']],
        ['value' => 'xheditor', 'text' => 'Xh编辑器 xheditor', 'data-type' => ['text', 'longtext']],
        ['value' => 'markdown', 'text' => 'MD编辑器 markdown', 'data-type' => ['text', 'longtext']],
        ['value' => 'select_dialog', 'text' => '选择对话框 select_dialog', 'data-type' => ['int(11)', 'varchar(100)']],
        ['value' => 'multiple', 'text' => '多选对话框 multiple', 'data-type' => ['text', 'varchar(200)', 'json']],
        ['value' => 'validcode', 'text' => '验证码 validcode'],
        ['value' => 'line', 'text' => '分割行 line'],
        ['value' => 'label', 'text' => '标签 label'],
        ['value' => 'button', 'text' => '按钮 button'],
        ['value' => 'plugin', 'text' => '插件 plugin', 'data-type' => ['text', 'json']],
    ],
    'search_type' => [
        ['value' => 'text', 'text' => '文本框 text', 'data-type' => ['varchar(100)', 'text']],
        ['value' => 'hidden', 'text' => '隐藏域 hidden', 'data-type' => ['int(11)', 'tinyint(4)', 'varchar(100)', 'float(18,2)', 'decimal(18,2)', 'double(18,2)', 'text', 'longtext', 'json']],
        ['value' => 'check', 'text' => '是否 check', 'data-type' => ['tinyint(1)']],
        ['value' => 'integer', 'text' => '整数 integer', 'data-type' => ['int(11)']],
        ['value' => 'number', 'text' => '小数 number', 'data-type' => ['decimal(18,2)', 'float(18,2)', 'double(18,2)']],
        ['value' => 'password', 'text' => '密码框 password', 'data-type' => ['varchar(100)']],
        ['value' => 'date', 'text' => '日期格式 date', 'data-type' => ['date', 'datetime', 'int(11)']],
        ['value' => 'datetime', 'text' => '时间格式 datetime', 'data-type' => ['datetime', 'int(11)']],
        ['value' => 'select', 'text' => '下拉框 select', 'data-type' => ['int(11)', 'varchar(100)']],
        ['value' => 'radiogroup', 'text' => '单选组 radiogroup', 'data-type' => ['int(11)', 'varchar(100)']],
        ['value' => 'checkgroup', 'text' => '多选组 checkgroup', 'data-type' => ['varchar(200)', 'int(11)', 'text', 'longtext', 'json']],
        ['value' => 'select_dialog', 'text' => '选择对话框 select_dialog', 'data-type' => ['int(11)', 'varchar(100)']],
        ['value' => 'linkage', 'text' => '联动下拉 linkage', 'data-type' => ['varchar(200)', 'text', 'json']],
        ['value' => 'button', 'text' => '按钮 button'],
    ],
    'support_action' => [
        ['value' => 'addAction', 'text' => '添加 add'],
        ['value' => 'editAction', 'text' => '编辑 edit'],
        ['value' => 'deleteAction', 'text' => '编辑 delete'],
        ['value' => 'sortAction', 'text' => '排序 sort'],
        ['value' => 'changeAllowAction', 'text' => '审核/撤销 changeAllow'],
        ['value' => 'deleteSelectAction', 'text' => '删除所选 deleteSelect'],
        ['value' => 'allowSelectAction', 'text' => '审核所选 allowSelect'],
        ['value' => 'unAllowSelectAction', 'text' => '撤销审核所选 unAllowSelect'],

    ]
];
